#finding a motif
s = 'CTCGGCCTCTCGGCCACACCTCGGCCCTCCTCGGCCCACTCGGCCCTGCTCGGCCAGCTCGGCCCTCGGCCGTCGTCCCTCGGCCCCTCGGCCCTCGGCCCCTCGGCCCTCGGCCCTCGGCCCTCTCGGCCCTCGGCCACTCGGCCATTTCTCGGCCTCTCGGCCCTCGGCCTGGCTCGGCCCTCGGCCTGTCTCGGCCATCCTCGGCCCTCTCGGCCCCTCGGCCCCGACTCGGCCCGGTCTCGGCCCTCGGCCTTACTCGGCCAGGGGTGAACTCGGCCGCATTCTCGGCCCTCGGCCCTCGGCCTCTCGGCCTATTGCTCGGCCATGGTCTCGGCCGATGCTCGGCCCTCGGCCAACTCGGCCCTCGGCCGCTCGGCCTGGCTCGGCCGGCTCGGCCTCTCGGCCAGTCTCGGCCACTCGGCCCTCGGCCCTCGGCCCTCGGCCCTCGGCCGGTTCTCGGCCGGACTCGGCCTAAGGGCTCGGCCTACACTCGGCCGACAAGCTCGGCCCTCGGCCCTCGGCCCTCGGCCCTCGGCCAAGACCATTGCATACATTCTCGGCCACAGCTCGGCCTGCGACTCGGCCGCTCGGCCGACTCGGCCACTCGGCCCTCAAAACCTCGGCCCTCGGCCCTCGGCCCTCGGCCTGCTACCTCGGCCACTCGGCCTGTTTTAGCCTCGGCCCTCGGCCGACTCGGCCTCTCGGCCGTCATCTCGGCCTCTCGGCCCTCGGCCACTCGGCCAGTCCTCGCTCGGCCCTCTCGGCCTGGTCTTACCTCGGCCGCTCTCGGCCACTCGGCCCCCCTCGGCCCTCGGCCGTTATTGCCGCAAGACTCGGCCTCCTCGGCCCGGACTCGGCCCGCACGGAAAGCAGCTCGGCCCATGCTGACAGGTCCTCGGCCGCTCGGCCCTCGGCCTATTCTCGGCCGCTCGGCC'
t = 'CTCGGCCCT'
pos = []

for i in range(0, len(s)):
    if i == len(s) - len(t):
        if s[i:] == t:
            pos.append(i+1)
    elif i == len(s) - (len(t) - 1):
        break
    else:
        if s[i:i + len(t)] == t:
            pos.append(i + 1)


for i in pos:
    print(i)

#finding a shared motif

