s = 'ACCAGGTTGGATCAGGCCATTTTCAGGACGCTCCAAAGGAACTGCTACGTACTCCACAGCTAAGTAGACCTATCGACACGAAGGCACATCAACAGGACTGCTGGGTCAATTCCCCGGTTTGACGTGGTGAGTCGAAAAAATCTCGAACCTGGTAGGTCATGCGTTCCCGAAATCGTGCCGGGCGTCCTCGAGTCGCAATATGACGCCAACTTAAGCCCGCGCCTTCGTCTCACACCCGTGTGGGGGCCGGGCCTTTGGTTGCAATCACCCGTCGTGGTTACTCCTAATGATTGAACGCCTAATCCACATGGCACCTTACTGAGATCAGAGCAGCTAAATCTTAATGTATTATTCGGTATCCTCCGACCCGCAGCCGGGCAAAAAAGGAAGGTTAGACTGTGTAACGTGAAATAAGGAGCTGGAAGGGTTAGGAATTTAGAATAGAATACTATGAGAAAAAATCAACGGGAGATACATTGCGGTCATGTCGGTATGACCTCCAGTGGAGTGGTGAGCAGGATTTGTGCATGCAGTTCATCCTATACGACGAGCGCGAGACCGTCCCCGAAGTGCAGTAGAATTCCTGACAGTGTTATGTTGGCTAAAATTCCCTGGGATATCGGTAGTGTGAACAACTTGCATGCGAGAGAAGCCGTCATACAAAGGAACACGCATGGCAATGTATATGTGTTCAGCGCTGCCAGATGTCGGTGCAGTAGCAATCTTGCAGCCTATAGCTGTCTCGTTGCTTTGTTGCGGAGTACATGTGGGCGAGTCTCTTGCTAGTGCAAGGAGCTACGAACAACTAGAATAAAGGGTGCTTTGAACGCGGCAACACGCCGCAACGAGAGCCGTCTGATGGATGGGCTGCGAGCTGTCGAACGGTGGAGTG'
sc = ''
for i in s:
    if i == 'A':
        sc += 'T'
    elif i == 'T':
        sc += 'A'
    elif i == 'C':
        sc += 'G'
    elif i == 'G':
        sc += 'C'

print(sc[::-1])